-- mapinfo.lua (Spring/Recoil SMF)
-- Generated by bar-map-generator
local mapinfo = {
  name        = "BAR_Generator_Validation",
  shortname   = "BAR_Generator_Validation",
  description = "Procedurally generated (land, temperate, mirror)",
  author      = "bar-map-generator",
  version     = "1",
  springmod   = "BAR",
  modtype     = 1,
  smf = {
    minheight = 0,
    maxheight = 600,
  },
  mapSize = {
    x = 384,
    z = 384,
  },
}
return mapinfo
