-- mapinfo.lua (Spring/Recoil SMF)
-- Generated by bar-map-generator
local mapinfo = {
  name        = "Procedural BAR Map",
  shortname   = "Procedural BAR Map",
  description = "Procedurally generated (land, desert, mirror)",
  author      = "bar-map-generator",
  version     = "1",
  springmod   = "BAR",
  modtype     = 1,
  startpic    = "map.png",
  smf = {
    minheight = 0,
    maxheight = 850,
  },
  mapSize = {
    x = 384,
    z = 384,
  },
}
return mapinfo
